### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by Vesulius** [asianomainen/RSA-Encrypt-Decrypt-KeyGen-tiralabra#1]
Tiralabra 2021 syksy
# Koodikatselmointi

Koodista oli juuri tätä kirjottaessani julkaistu uusi versio. Latasin tämänkin mutta uskon että kommentit koskevat molempia versiota.

#### Kokonaisuus
Projektin käyttäminen oli helppoa ja intuitiivista. Käytetty grafiikka on selkeää ja toimiva demoamista varten. Projektin käynnistys ja testaus toimi mavella kuten kuvattu. Vaikka komento mvn jacoco:report meni läpi ilman virheitä en saanut generoitua javadoccia koneellani. (Käytin testaamiseen vscodea). Tekstin salaus ja salauksen poisto toimivat ongelmitta suurillakin syötteillä.

#### Koodi
Ohjelmiston rakenne on jaettu järkevästi pakkauksiin ja luokkiin. Luokat on jaettu yksittäisiin metodeihin  single responsebility -perjaatetta noudattaen. Koodia on helppo lukea hyvän dokumentaation ja kommenttien ansiosta. Kommentteja on runsaasti ja ne havainnollistavat ohjelman toimintaa.  Koodi itsesään on myös selkeästi kirjoitettu ja muuttujiin on valittu hyvin kuvaavat nimet. 

#### Testaus
Testit ovat kattavat koko luokan ja ovat nimetty selkeästi. KeyGenerator -luokassa yksittäisiä metodeja olisi voitu testata erikseen. Esim meneekö javalla sattumanvaraisesti generoitu alkuluku läpi Miller-Rabin testistä? Entä generoitu yhdistetty luku? 
Javadocin kirjoitus englanniksi ja kommenttien suomeksi on yllättävää mutta itseäni ei haitannut.

#### Yleisesti
Projektin tämänhetkiset toiminnallisuudet toimivat hyvin ja kokonaisuudessaan projekti näyttää olevan hyvällä mallilla. Tsemppiä!

Projekti ladattu 18.00 9.10.2021

**Comment by asianomainen** [comment]
Kiitos vertaisarvioinnista! 

Lisäsin ohjelmaani ehdottamasi KeyGenerator-luokan testit ja yhtenäistin ohjelman kommentointia ja javadocia muuttamalla javadocin myös suomeksi.
