### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by arppuri** [asianomainen/RSA-Encrypt-Decrypt-KeyGen-tiralabra#2]
Käyttöliittymä on selkeä ja ohjelma toimii hyvin. Myös ohjelmiston rakenne on selkeä ja koodi on helposti luettavaa ja hyvin kommentoitua. Testaus vaikuttaa kattavalta. Kaikkiaan hyvin tehty, selkeä ja kattava projekti mielenkiintoisesta aiheesta. (Ainoa pieni huomautuksenaihe määrittelydokumentista, jossa lähteet voisi selkeyden vuoksi luetella omilla riveillään ja kenties muotoilla kuten toteutusdokumentissa, mutta tämä on vain pieni muotoseikka.) Hyvää työtä!

Projekti ladattu 18.10.2021 (pahoittelen arvion viivästymistä).

**Comment by asianomainen** [comment]
Kiitos vertaisarvioinnista! Lähteet määrittelydokumentissa korjattu nyt niin, että ne näkyvät omilla riveillään :+1:
